plantrip_filnal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    
    # path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls, name="admin-views"),
    path('', include('user_app.api.urls')),
    path('', include('businessplace_app.api.urls')),
    path('', include('trip_app.api.urls')),
    path('', include('payment_app.api.urls')),
    path('test/', include('test_app.urls'), name="test_index"),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from test_app.views import *

app_name = 'test'

urlpatterns = [
    path('index_business/', index, name='test_index'),
    path('index_admin/', index_admin, name='test_index_admin'),
    path('login/', index_login, name='test_index_login'),
    path('logout/', logout_user, name='test_logout'),
    path('singup/', signup_business, name='test_singup_business'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    path('addnew', addnew, name='test_addnew'),
    path('edit/<int:pk>/', edit, name='test_edit'),
    path('update/<int:pk>/', update, name='test_update'),
    path('delete/<int:pk>', delete, name='test_delete'),
    
    path('img/<int:pk>/', image_view, name='test_image_view'),
    path('sql/', get_list_place, name='test_sql'),
    
    path('payment_add/', payment_create, name='test_payment_create'),
    path('payment/', index_payment, name='test_index_payment'),
    path('payment/<int:pk>', payment, name='test_payment'),
    path('update_payment/<int:pk>', update_payment, name='test_update_payment'),
    path('update_profile/', update_profile, name='test_update_profile'),
    
    path('get_place_distance/<int:pk>/', get_list_place_with_distance, name='test_get_place_distance'),
    path('get_place_distance2/<int:pk>/<path:lat>/<path:lng>/<str:username>/', get_list_place_with_distance2, name='test_get_place_distance2'),
    path('get_sortPlace_with_tripBudget/<int:pk>/', getSortPlaceWithTripBudget, name='test_get_sortPlace_with_tripBudget'),
    path('get_sortPlace_with_usePlace/', getSorPlacetWithUsePlace, name='test_get_sortPlace_with_usePlace'),
    
    path('get_sortTrip_with_useTrip/', getSorTriptWithUseTrip, name='test_get_sortTrip_with_useTrip'),
    path('get_sortTrip_with_tripBudget/<path:budget>/', getSorTriptWithtripBudget, name='test_get_sortTrip_with_tripBudget'),
    path('get_list_trip_detail_clone/<int:pk>/', getListTripDetailClone, name='test_get_list_trip_detail_clone'),
    path('get_list_rac_place/<int:pk>/', getListRacPlace, name='test_get_list_rac_place'),
    
    path('get_list_trip_user_and_pic1/<str:username>/', getListTripUserAndPic1, name='test_get_list_trip_user_and_pic1'),
    
    path(
        'add_create_trip_clone/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<str:date_start>/<str:date_end>/<int:pkClone>/<str:username>/', 
        TripCloneViewAV.as_view(), 
        name='test_add_create_trip_clone'),
    
    path('add_create_trip_detail_clone/<int:pkMain>/<int:pkClone>/', addTripCloneDetail, name='test_add_create_trip_detail_clone'),
    
    path('report_business/', report, name='test_report_business'),
    path('report_business/<int:pk>/', open_report, name='test_open_report_business'),
    
    path('chkIn_TripDetailID/<int:pk>/<int:chkIn>/', TripDetailChkIn.as_view(), name='chkIn_TripDetailID'),
    path('chkIn_place_in_trip/<int:trip_id>/<int:place_id>/', chkPlaceInTrip, name='chkIn_place_in_trip'),
    path('chkIn_trip_detail/<int:pk>/', chkTripDetail, name='chkIn_trip_detail'),
    
    path('delete_trip/<int:pk>/', TripDeleteAV.as_view(), name='delete_trip'),
    path('add_rac_place/<int:score>/<str:comment>/<int:place_id>/<str:username>/', RacPlaceAV.as_view(), name='add_rac_place'),
    path(
        'update_trip_detail/<int:pk>/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<int:permission>/<str:username>/<str:date_end>/<str:date_start>/', 
         TripDetailUpdateAV.as_view(), 
         name='update_trip_detail'
    ),
]

user_app/api/urls.py
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path
from plantrip_filnal import settings
from user_app.api.views import *

from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', home_view, name='home-view'),

    path('login/', obtain_auth_token, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='myapp_logout'),

    path('user_all/', UserViewAV.as_view(), name='user-all'),
    path('user/<int:pk>/', UserViewDetailAV.as_view(), name='user-detail'),
    path('user/<str:username>/', UserViewDetail.as_view(), name='user-detail-view'),
    
    path('about_us/', about_us_view, name='about-us-view'),
    path('chk_group_id/<str:username>/', ChkGroupID.as_view(), name='chkgroupid-view'),
]

user_app/models.py
import datetime
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from django.contrib.auth.models import User
from django.db import models

from businessplace_app.models import BusinessPlace

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        
class AccountDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    address = models.TextField(null=True, blank=True)
    
    def __str__(self) :
        return str(self.user.username)
    

user_app/api/views.py
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework import status

from user_app import models
from django.shortcuts import redirect, render
from django.urls import reverse
from rest_framework import generics
from django.contrib.auth.models import User, Group

from user_app.api.serializers import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


def home_view(request):
    if request.user.is_authenticated:
        user = request.user
        if user.is_staff:
            # admin_login_url = reverse('admin:login')
            # return redirect(admin_login_url)
            return redirect('/test/index_admin/')
        elif user.groups.filter(name="business").exists():
            return redirect('/test/index_business/')
        else:
            messages.warning(request, 'สำหรับผู้ใช้กิจการและผู้ดูแลระบบเท่านั้น.')
            return render(request, '../templates/main/home.html', {})
    else:        
        return render(request, '../templates/main/home.html', {})
    

def about_us_view(request):
    
    return render(request, '../templates/main/about_us_page.html', {})

class ChkGroupID(generics.ListAPIView):
    
    serializer_class = UserGroupIdSerializer
    
    def get_queryset(self):
        username = self.kwargs['username']
        return User.objects.filter(username=username)

class UserViewAV(APIView):
    
    def get(self, request):
        users = User.objects.all()
        serializer = UserSerializer(users, many=True)
        return Response(serializer.data)

class UserViewDetailAV(APIView):
    
    def get(self, request, pk):
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist :
            return Response({'error': 'user not found'}, status=status.HTTP_404_NOT_FOUND)
        serializer = UserSerializer(user)
        return Response(serializer.data)
    
    def put(self, request, pk):
        user = User.objects.get(pk=pk)
        serializer = UserAccountSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, pk):
        user = User.objects.get(pk=pk)
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
class UserViewDetail(generics.ListAPIView):
    
    serializer_class = UserSerializer
    
    def get_queryset(self):
        username = self.kwargs['username']
        return User.objects.filter(username=username)
    

@api_view(['POST', ])
def logout_view(request):

    if request.method == 'POST':
        request.user.auth_token.delete()
        return Response(status=status.HTTP_200_OK)


@api_view(['POST', ])
def registration_view(request):

    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)

        data = {}

        if serializer.is_valid():
            
            account = serializer.save()
            g = Group.objects.get(name="traveler")
            
            account.groups.add(g)

            data['response'] = "Registration Successful!"
            data['username'] = account.username
            data['email'] = account.email

            token = Token.objects.get(user=account).key
            data['token'] = token

        else:
            data = serializer.errors

        return Response(data, status = status.HTTP_201_CREATED)

user_app/views.py
from django.shortcuts import render

# Create your views here.

user_app/templates/main/about_us_page.html
{% extends 'main/base.html' %} {% block title %}หน้าแรก{% endblock %} {% block content%}

<!-- About Content -->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <img src="https://raw.githubusercontent.com/MPR2014v8/PlanTripFinal/main/static/media/images/homepage.png" class="img-fluid" alt="About Us">
        </div>
        <div class="col-lg-6">
            <h2 class="mb-4">เกี่ยวกับเรา</h2>
            <p>เว็บไชต์นี้ถูกพัตนาขึ้นมาเพิ่อใช้ในรายวิชาโครงงาน</p>
            <p>พัตนาขึ้นมาโดย</p>
            <p>นายวชิระ ทองเลิศ 64040249107</p>
            <p>นางสาวธนัชภร์ณ์ อาจกมล 63040249113</p>
            <p>คณะวิทยาศาสตร์ สาขาวิทยาการคอมพิวเตอร์ มหาลัยราชภัฏอุดรธานี</p>
            <br>
            <p>สำหรับผู้ประกอบการที่ต้องการสมัครใช้บริการ กรุณาติดต่อเรา.</p>
            <p>อีเมลสำหรับติดต่อ : 64040249107@udru.ac.th</p>
        </div>
    </div>
</div>

{% endblock %}

user_app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- bootstrap CND -->
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <style>
      @import url("https://fonts.googleapis.com/css2?family=Prompt&display=swap");
      * {
        font-family: "Prompt", sans-serif;
      }
      html {
        box-sizing: border-box;
        font-size: 16px;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }

      body,
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p,
      ol,
      ul {
        margin: 0;
        padding: 0;
        font-weight: normal;
      }

      ol,
      ul {
        list-style: none;
      }

      img {
        max-width: 100%;
        height: auto;
      }
    </style>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid text-white">
        <div>
          <a href="{% url 'user:home-view' %}" style="text-decoration: none">
            <h4 class="text-white">
              Plan<span class="text-primary">Trip</span>
            </h4>
          </a>
        </div>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'user:home-view' %}"
                >หน้าหลัก</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link text-white"
                href="{% url 'user:about-us-view' %}"
                >เกี่ยวกับเรา</a
              >
            </li>
            <li class="nav-item bg-primary">
              <a
                class="nav-link text-white"
                href="{% url 'test:test_index_login' %}"
                >สำหรับผู้ประกอบการ</a
              >
            </li>
            <li class="nav-item bg-danger">
              <a class="nav-link text-white" href="{% url 'admin:index' %}"
                >สำหรับผู้ดูแลระบบ</a
              >
            </li>
            <!-- Add more menu items as needed -->
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% for message in messages %}
      <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">×</span>
          </button>
          {{ message }}
        </div>
      </div>
      {% endfor %} 
      {% block content %} {% endblock %}
    </div>

    <!-- bootstrap CND -->
    <script
      src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"
      integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.7.0.js"
      integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user_app/templates/main/home.html
{% extends 'main/base.html' %} {% block title %}หน้าแรก{% endblock %} 
{% block content %} {% load static %}
<div class="row">
  <img
    src="https://raw.githubusercontent.com/MPR2014v8/PlanTripFinal/main/static/media/images/homepage.png"
    id="homepic"
    style="
      height: 100%;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    "
  />
</div>

<div
  class="d-flex flex-row m-5 justify-content-around row border-bottom"
  id="about-website"
>
  <div class="d-flex flex-column col-4">
    <div class="card flex-fill" style="width: 25rem">
      <img
        src="https://github.com/MPR2014v8/PlanTripFinal/blob/main/static/media/images/traveler.jpg?raw=true"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h4 class="card-title">นักท่องเที่ยว</h4>
        <p class="card-text">
          ได้เปิดประสบการณ์การการท่องเที่ยวใหม่ๆ ตลอดทุกการเดินทาง
        </p>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column col-4">
    <div class="card flex-fill" style="width: 25rem">
      <img
        src="https://github.com/MPR2014v8/PlanTripFinal/blob/main/static/media/images/business.jpg?raw=true"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h4 class="card-title">ผู้ประกอบการ</h4>
        <p class="card-text">
          ได้โปรโมทกิจการของตัวเองและสามารถเข้าถึงนักท่องเที่ยวใหม่ๆได้มากขึ้น
        </p>
      </div>
    </div>
  </div>
  <div class="d-flex flex-column col-4">
    <div class="card flex-fill" style="width: 25rem">
      <img
        src="https://github.com/MPR2014v8/PlanTripFinal/blob/main/static/media/images/village.jpg?raw=true"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h4 class="card-title">ชุมชน</h4>
        <p class="card-text">
          ได้รับการช่วยกระตุ้นเศรษฐกิจ
          เมื่อมีนักท่องเที่ยวสังคมและชุมชนก็พอมีรายได้เลี้ยงตัวเอง
        </p>
      </div>
    </div>
  </div>
</div>

<div class="d-flex pl-5 pb-5">
  <div class="p-2">
    <form action="https://drive.google.com/drive/folders/1QapSphfIzfOkeBeB6Vf1gFBaqEXlMg6K?usp=sharing">
      <button
        class="btn btn-outline-success flex-shrink-0 btn bg-sucess btn-sm"
        type="submit"
      >
        <i class="bi bi-phone me-1"></i>
        โหลดแอพพิเคชั่น สำหรับนักท่องเที่ยว
      </button>
    </form>
  </div>
  <div class="p-2">
    <form action="{% url 'user:about-us-view' %}">
      <button
        class="btn btn-outline-danger flex-shrink-0 btn btn-sm"
        type="submit"
      >
        <i class="bi bi-building me-1"></i>
        สมัครใช้บริการสำหรับผู้ประกอบการ
      </button>
    </form>
  </div>
</div>

<!-- About Content -->
<div class="container-fluid pb-5 pl-5">
  <div class="row">
    <div class="col-lg-6">
      <img
        src="https://raw.githubusercontent.com/MPR2014v8/PlanTripFinal/main/static/media/images/homepage.png"
        class="img-fluid"
        alt="About Us"
      />
    </div>
    <div class="col-lg-6">
      <h2 class="mb-4">เกี่ยวกับเรา</h2>
      <p>เว็บไชต์นี้ถูกพัตนาขึ้นมาเพิ่อใช้ในรายวิชาโครงงาน</p>
      <p>พัตนาขึ้นมาโดย</p>
      <p>นายวชิระ ทองเลิศ 64040249107</p>
      <p>นางสาวธนัชภร์ณ์ อาจกมล 63040249113</p>
      <p>คณะวิทยาศาสตร์ สาขาวิทยาการคอมพิวเตอร์ มหาลัยราชภัฏอุดรธานี</p>
      <br />
      <p>อีเมลสำหรับติดต่อ : 64040249107@udru.ac.th</p>
    </div>
  </div>
</div>

{% endblock %}

user_app/templates/main/place.html
{% extends 'main/base.html' %} {% block title %}สถานที่{% endblock %} 
{% block content %}
<h1 class="mt-5 mb-5">สถานที่ทั้งหมด</h1>
<div class="row justify-content-center">
  {% for x in pictures %}
  <div class="col-sm-4" style="width: 18rem">
    <div class="card">
      {% load static %}
      <img
        class="card-img-top"
        src="{{ x.image.url }}"
        alt="Card image cap"
        style="width: 100%; height: 18vw; object-fit: cover"
      />
      <div class="card-body">
        <h5
          class="card-title"
          style="
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 3; /* number of lines to show */
            line-clamp: 2;
            -webkit-box-orient: vertical;
          "
        >
          {{ x.place.name}}
        </h5>
        <p
          class="card-text"
          style="
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 3; /* number of lines to show */
            line-clamp: 2;
            -webkit-box-orient: vertical;
          "
        >
          {{ x.place.description }}
        </p>
        <a href="{% url 'place_detail' id=x.place.id %}" class="btn btn-primary">ดูรายละเอียด</a>
      </div>
    </div>
    <br />
  </div>
  {% endfor %}
</div>

{% endblock %}

user_app/templates/main/place_detail.html
{% extends 'main/base.html' %} {% block title %}รายละเอียดสถานที่{% endblock %} 
{% block content %}
<section class="fdb-block py-0">
    <div class="container" style="background-color: rgb(237, 237, 237)">
      <div class="row justify-content-center py-5">
        <div class="col-12 col-md-10 col-lg-8 text-center">
          <div class="fdb-box">
            <div id="gallery-slides" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#gallery-slides" data-slide-to="0" class="active"></li>
                {% for x in pic_gallery %}
                <li data-target="#gallery-slides" data-slide-to="{{ forloop.couter }}"></li>
                {% endfor %}
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <a href="{{ pic_main.image.url }}">
                    <img
                      class="d-block w-100 h-50 fit-image"
                      src="{{ pic_main.image.url }}"
                    />
                  </a>
                </div>
                {% for x in pic_gallery %}
                <div class="carousel-item">
                  <a href="{{ x.image.url }}">
                    <img
                      class="d-block w-100 h-50 fit-image"
                      src="{{ x.image.url }}"
                    />
                  </a>
                </div>
                {% endfor %}
              </div>
              <a
                class="carousel-control-prev"
                href="#gallery-slides"
                role="button"
                data-slide="prev"
              >
                <span
                  class="carousel-control-prev-icon"
                  aria-hidden="true"
                ></span>
                <span class="sr-only">Previous</span>
              </a>
              <a
                class="carousel-control-next"
                href="#gallery-slides"
                role="button"
                data-slide="next"
              >
                <span
                  class="carousel-control-next-icon"
                  aria-hidden="true"
                ></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
  
            <br />
            <h1 class="p-4">{{ place.name }}</h1>
            <p class="lead">{{ place.description }}</p>
            <p class="mt-4">
              <a class="btn btn-primary" href="{{ mediaVR.link }}">Virtual Reality</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}