businessplace_app/api/urls.py
from django.urls import path
from businessplace_app.api.views import *

app_name = 'business'

urlpatterns = [
    path('business_home/', business_home_view, name='businessHomeView'),
    path('business/login/', business_login_view, name='businessLoginView'),
    
    path('business-all/', BusinessPlaceViewAV.as_view(), name='businessView-all'),
    path('business-all-join/', get_list_place, name='businessView-all-join'),
    path('business/', BusinessPlaceSearchView.as_view(), name='businessView'),
    path('business-create/', BusinessPlaceCreateViewAV.as_view(), name='businessCreateView'),
    path('business-update/<int:id>/', BusinessPlaceUpateViewAV.as_view(), name='businessUpateView'),
    path('business/<int:id>/', BusinessPlaceDetailView.as_view(), name='businessDetailView'),
    
    path('business/place/', business_place_view, name='businessPlaceView'),
    path('business/place-user/<str:username>/', BusinessPlaceUserViewAV.as_view(), name='businessPlaceUserView'),
    path('business/place/pictures/', business_place_pic_view,name='businessPlacePicView'),
    path('business/place/payment/', business_place_payment_view, name='businessPlacePaymentView'),
    
    path('business/rac-all/', RatingAndCommentViewAV.as_view(), name='racView-all'),
    path('business/rac/', RatingAndCommentSearchView.as_view(), name='racView'),
    
    path('business/rac/<int:id>/', RatingAndCommentDetailView.as_view(), name='racDetailView'),
    
    path('business/rac/user=<int:id_user>,place=<int:id_place>/', RatingAndCommentFilterPlaceUser.as_view(), name='racUserPlaceView'),
    path('business/rac/place=<int:id_place>/', RatingAndCommentPlace.as_view(), name='racPlaceView'),
    
    # path('business/chkin-all/', RatingAndCommentViewAV.as_view(), name='chkinView-all'),
    # path('business/chkin/', RatingAndCommentSearchView.as_view(), name='chkinView'),
    # path('business/chkin/<int:id>/', RatingAndCommentDetailView.as_view(), name='chkinDetailView'),
    
]

plantrip_filnal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    
    # path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls, name="admin-views"),
    path('', include('user_app.api.urls')),
    path('', include('businessplace_app.api.urls')),
    path('', include('trip_app.api.urls')),
    path('', include('payment_app.api.urls')),
    path('test/', include('test_app.urls'), name="test_index"),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from test_app.views import *

app_name = 'test'

urlpatterns = [
    path('index_business/', index, name='test_index'),
    path('index_admin/', index_admin, name='test_index_admin'),
    path('login/', index_login, name='test_index_login'),
    path('logout/', logout_user, name='test_logout'),
    path('singup/', signup_business, name='test_singup_business'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    path('addnew', addnew, name='test_addnew'),
    path('edit/<int:pk>/', edit, name='test_edit'),
    path('update/<int:pk>/', update, name='test_update'),
    path('delete/<int:pk>', delete, name='test_delete'),
    
    path('img/<int:pk>/', image_view, name='test_image_view'),
    path('sql/', get_list_place, name='test_sql'),
    
    path('payment_add/', payment_create, name='test_payment_create'),
    path('payment/', index_payment, name='test_index_payment'),
    path('payment/<int:pk>', payment, name='test_payment'),
    path('update_payment/<int:pk>', update_payment, name='test_update_payment'),
    path('update_profile/', update_profile, name='test_update_profile'),
    
    path('get_place_distance/<int:pk>/', get_list_place_with_distance, name='test_get_place_distance'),
    path('get_place_distance2/<int:pk>/<path:lat>/<path:lng>/<str:username>/', get_list_place_with_distance2, name='test_get_place_distance2'),
    path('get_sortPlace_with_tripBudget/<int:pk>/', getSortPlaceWithTripBudget, name='test_get_sortPlace_with_tripBudget'),
    path('get_sortPlace_with_usePlace/', getSorPlacetWithUsePlace, name='test_get_sortPlace_with_usePlace'),
    
    path('get_sortTrip_with_useTrip/', getSorTriptWithUseTrip, name='test_get_sortTrip_with_useTrip'),
    path('get_sortTrip_with_tripBudget/<path:budget>/', getSorTriptWithtripBudget, name='test_get_sortTrip_with_tripBudget'),
    path('get_list_trip_detail_clone/<int:pk>/', getListTripDetailClone, name='test_get_list_trip_detail_clone'),
    path('get_list_rac_place/<int:pk>/', getListRacPlace, name='test_get_list_rac_place'),
    
    path('get_list_trip_user_and_pic1/<str:username>/', getListTripUserAndPic1, name='test_get_list_trip_user_and_pic1'),
    
    path(
        'add_create_trip_clone/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<str:date_start>/<str:date_end>/<int:pkClone>/<str:username>/', 
        TripCloneViewAV.as_view(), 
        name='test_add_create_trip_clone'),
    
    path('add_create_trip_detail_clone/<int:pkMain>/<int:pkClone>/', addTripCloneDetail, name='test_add_create_trip_detail_clone'),
    
    path('report_business/', report, name='test_report_business'),
    path('report_business/<int:pk>/', open_report, name='test_open_report_business'),
    
    path('chkIn_TripDetailID/<int:pk>/<int:chkIn>/', TripDetailChkIn.as_view(), name='chkIn_TripDetailID'),
    path('chkIn_place_in_trip/<int:trip_id>/<int:place_id>/', chkPlaceInTrip, name='chkIn_place_in_trip'),
    path('chkIn_trip_detail/<int:pk>/', chkTripDetail, name='chkIn_trip_detail'),
    
    path('delete_trip/<int:pk>/', TripDeleteAV.as_view(), name='delete_trip'),
    path('add_rac_place/<int:score>/<str:comment>/<int:place_id>/<str:username>/', RacPlaceAV.as_view(), name='add_rac_place'),
    path(
        'update_trip_detail/<int:pk>/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<int:permission>/<str:username>/<str:date_end>/<str:date_start>/', 
         TripDetailUpdateAV.as_view(), 
         name='update_trip_detail'
    ),
]

user_app/api/urls.py
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path
from plantrip_filnal import settings
from user_app.api.views import *

from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', home_view, name='home-view'),

    path('login/', obtain_auth_token, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='myapp_logout'),

    path('user_all/', UserViewAV.as_view(), name='user-all'),
    path('user/<int:pk>/', UserViewDetailAV.as_view(), name='user-detail'),
    path('user/<str:username>/', UserViewDetail.as_view(), name='user-detail-view'),
    
    path('about_us/', about_us_view, name='about-us-view'),
    path('chk_group_id/<str:username>/', ChkGroupID.as_view(), name='chkgroupid-view'),
]

businessplace_app/api/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    # You can add additional fields or customize the form here if needed
    pass

businessplace_app/api/views.py
import json
from django.db import connection
from django.http import HttpResponse

from django.db.models import Q
from django.forms import ValidationError
from django.shortcuts import render
from rest_framework.views import APIView
from businessplace_app.api.serializers import BusinessPlaceSerializer, RatingAndCommentSerializer
from rest_framework.response import Response
from businessplace_app.models import BusinessPlace, RatingAndComment
from rest_framework import filters
from rest_framework import generics
from rest_framework import status


def get_list_place(request):

    data_list = []
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 
                bp.id as place_id, bp.name as place_name, detail, lat, lng, district,
                address, timeOpen, timeClose, website,
                type_id, bt.name as type_name,
                place_user_id, au.username, au.email,
                pic1, pic2, pic3, vr
            FROM PLANTRIPDB.BusinessPlace as bp
            INNER JOIN PLANTRIPDB.auth_user as au
                ON bp.place_user_id = au.id 
            INNER JOIN PLANTRIPDB.BusinessType as bt
                ON bp.type_id = bt.id               
        """)
        data_read = cursor.fetchall()
        print(data_read[0])

    for row in data_read:
        data_list.append({
            "place_id": str(row[0]),
            "place_name": str(row[1]),
            "detail": str(row[2]),
            "lat": str(row[3]),
            "lng": str(row[4]),
            "district": str(row[5]),
            "address": str(row[6]),
            "timeOpen": str(row[7]),
            "timeClose": str(row[8]),
            "website": str(row[9]),
            "type_id": str(row[10]),
            "type_name": str(row[11]),
            "place_user_id": str(row[12]),
            "username": str(row[13]),
            "email": str(row[14]),
            "pic1": str(row[15]),
            "pic2": str(row[16]),
            "pic3": str(row[17]),
            "vr": str(row[-1]),
        })

    json_data = json.dumps(data_list, ensure_ascii=False).encode('utf-8')
    response = HttpResponse(
        json_data, content_type='application/json; charset=utf-8')

    return response

def business_login_view(request):
    return render(request, '../templates/business_login_page.html', {})

def business_home_view(request):
    return render(request, '../templates/business_home_page.html', {})

def business_place_view(request):
    return render(request, '../templates/business_place_manage_page.html', {})

def business_place_pic_view(request):
    return render(request, '../templates/business_place_pic_manage.html', {})

def business_place_payment_view(request):
    return render(request, '../templates/business_place_payment_manage.html', {})

class BusinessPlaceCreateViewAV(APIView):
    
    def get(self, request):
        place = BusinessPlace.objects.all()
        serializer = BusinessPlaceSerializer(place, many=True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = BusinessPlaceSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class BusinessPlaceUpateViewAV(APIView):
    def put(self, request, id):
        place = BusinessPlace.objects.get(id=id)
        serializer = BusinessPlaceSerializer(place, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, id):
        place = BusinessPlace.objects.get(id=id)
        place.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class BusinessPlaceUserViewAV(generics.ListAPIView):
    serializer_class = BusinessPlaceSerializer

    def get_queryset(self):
        username = self.kwargs['username']
        return BusinessPlace.objects.filter(place_user__username=username)

class BusinessPlaceViewAV(APIView):
    
    def get(self, request):
        users = BusinessPlace.objects.all()
        serializer = BusinessPlaceSerializer(users, many=True)
        return Response(serializer.data)
    
class BusinessPlaceSearchView(generics.ListAPIView):
    queryset = BusinessPlace.objects.all()
    serializer_class = BusinessPlaceSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']
    
class BusinessPlaceDetailView(generics.ListAPIView):
    serializer_class = BusinessPlaceSerializer

    def get_queryset(self):
        id = self.kwargs['id']
        return BusinessPlace.objects.filter(id=id)
    
class RatingAndCommentViewAV(APIView):
    
    def get(self, request):
        users = RatingAndComment.objects.all()
        serializer = RatingAndCommentSerializer(users, many=True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = RatingAndCommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
class RatingAndCommentSearchView(generics.ListAPIView):
    queryset = RatingAndComment.objects.all()
    serializer_class = RatingAndCommentSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['place__name']
    
class RatingAndCommentDetailView(APIView):
    serializer_class = RatingAndCommentSerializer

    def get(self, request, id):
        try:
            rac = RatingAndComment.objects.get(id=id)
        except RatingAndComment.DoesNotExist :
            return Response({'error': 'RatingAndComment not found'}, status=status.HTTP_404_NOT_FOUND)
        serializer = RatingAndCommentSerializer(rac)
        return Response(serializer.data)

    def put(self, request, id):
        rac = RatingAndComment.objects.get(id=id)
        serializer = RatingAndCommentSerializer(rac, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, id):
        rac = RatingAndComment.objects.get(id=id)
        rac.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
class RatingAndCommentFilterPlaceUser(generics.ListAPIView):
    serializer_class = RatingAndCommentSerializer

    def get_queryset(self):
        id_user = self.kwargs['id_user']
        id_place = self.kwargs['id_place']
        return RatingAndComment.objects.filter(user__id=id_user).filter(place__id=id_place)
    
class RatingAndCommentPlace(generics.ListAPIView):
    serializer_class = RatingAndCommentSerializer

    def get_queryset(self):
        id_place = self.kwargs['id_place']
        return RatingAndComment.objects.filter(place__id=id_place)
    






# class checkInLocationPlaceViewAV(APIView):
    
#     def get(self, request):
#         users = RatingAndComment.objects.all()
#         serializer = RatingAndCommentSerializer(users, many=True)
#         return Response(serializer.data)
    
#     def post(self, request):
#         serializer = RatingAndCommentSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
# class checkInLocationPlaceSearchView(generics.ListAPIView):
#     queryset = RatingAndComment.objects.all()
#     serializer_class = RatingAndCommentSerializer
#     filter_backends = [filters.SearchFilter]
#     search_fields = ['place__name']
    
# class checkInLocationPlaceDetailView(APIView):
#     serializer_class = RatingAndCommentSerializer

#     def get(self, request, id):
#         try:
#             rac = RatingAndComment.objects.get(id=id)
#         except RatingAndComment.DoesNotExist :
#             return Response({'error': 'RatingAndComment not found'}, status=status.HTTP_404_NOT_FOUND)
#         serializer = RatingAndCommentSerializer(rac)
#         return Response(serializer.data)

#     def put(self, request, id):
#         rac = RatingAndComment.objects.get(id=id)
#         serializer = RatingAndCommentSerializer(rac, data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         else:
#             return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#     def delete(self, request, id):
#         rac = RatingAndComment.objects.get(id=id)
#         rac.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)

businessplace_app/views.py
from django.shortcuts import render

# Create your views here.

businessplace_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- bootstrap CND -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <style>
      @import url("https://fonts.googleapis.com/css2?family=Prompt&display=swap");
      * {
        font-family: "Prompt", sans-serif;
      }
      html {
        box-sizing: border-box;
        font-size: 16px;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }

      body,
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p,
      ol,
      ul {
        margin: 0;
        padding: 0;
        font-weight: normal;
      }

      ol,
      ul {
        list-style: none;
      }

      img {
        max-width: 100%;
        height: auto;
      }
    </style>

    <title>{% block title %}My Site{% endblock %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div>
          <a href="{% url 'user:home-view' %}" style="text-decoration: none">
            <h4 class="text-white">
              Plan<span class="text-primary">Trip</span>
              สำหรับผู้ประกอบการ
            </h4>
          </a>
        </div>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link text-white" href="#">หน้าหลัก</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">โปรไฟล์</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">จัดการกิจการ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">ชำระค่าบริการ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">รายงาน</a>
            </li>
            <!-- Add more menu items as needed -->
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid m-0">
      {% block content-head %} {% endblock %}
    </div>
    <div class="container">
      {% block content %} {% endblock %}
    </div>

    <!-- bootstrap CND -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

businessplace_app/templates/business_home_page.html
{% extends 'base.html' %} {% block title %}หน้าแรก{% endblock %} 
{% block content %}

<br>
<h1>Business Person | หน้าแรก</h1>
<br>
<hr>
<br>
<div class="font-weight-bold">
    <a href="{% url 'business:businessPlaceView' %}"><span>จัดการกิจการ</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'business:businessPlacePicView' %}"><span>จัดการรูปภาพกิจการ</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'business:businessPlacePaymentView' %}"><span>จัดการค่าบริการ</span></a>
</div>

{% endblock %}

businessplace_app/templates/business_login_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <!-- Include the Bootstrap CSS stylesheet -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        @import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css");
        @import url("https://fonts.googleapis.com/css2?family=Prompt&display=swap");
        * {
          font-family: "Prompt", sans-serif;
        }
        html {
          box-sizing: border-box;
          font-size: 16px;
        }
  
        *,
        *:before,
        *:after {
          box-sizing: inherit;
        }
  
        body,
        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        p,
        ol,
        ul {
          margin: 0;
          padding: 0;
          font-weight: normal;
        }
  
        ol,
        ul {
          list-style: none;
        }
  
        img {
          max-width: 100%;
          height: auto;
        }

      </style>
  
</head>
<body>

<div class="container p-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4>ลงชื่อเข้าสู่ระบบ | สำหรับผู้ประกอบการ</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Include the Bootstrap JS scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

businessplace_app/templates/business_place_manage_page.html
{% extends 'base.html' %} {% block title %}หน้าแรก{% endblock %} 
{% block content %}

<br>
<h1>Business Person | จัดการกิจการ</h1>
<br>
<hr>
<br>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>เพิ่มกิจการ</span></a>
  </div>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>แก้ไขกิจการ</span></a>
</div>

{% endblock %}

businessplace_app/templates/business_place_payment_manage.html
{% extends 'base.html' %} {% block title %}หน้าแรก{% endblock %} 
{% block content %}

<br>
<h1>Business Person | จัดการชำระค่าบรืการ</h1>
<br>
<hr>
<br>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>เพิ่มหลักฐาน</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>แก้ไขหลักฐาน</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>ลบหลักฐาน</span></a>
</div>

{% endblock %}

businessplace_app/templates/business_place_pic_manage.html
{% extends 'base.html' %} {% block title %}หน้าแรก{% endblock %} 
{% block content %}

<br>
<h1>Business Person | จัดการรูปกิจการ</h1>
<br>
<hr>
<br>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>เพิ่มรูปกิจการ</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>แก้ไขรูปกิจการ</span></a>
</div>
<div class="font-weight-bold">
    <a href="{% url 'admin:index' %}"><span>ลบรูปกิจการ</span></a>
</div>

{% endblock %}