plantrip_filnal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    
    # path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls, name="admin-views"),
    path('', include('user_app.api.urls')),
    path('', include('businessplace_app.api.urls')),
    path('', include('trip_app.api.urls')),
    path('', include('payment_app.api.urls')),
    path('test/', include('test_app.urls'), name="test_index"),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from test_app.views import *

app_name = 'test'

urlpatterns = [
    path('index_business/', index, name='test_index'),
    path('index_admin/', index_admin, name='test_index_admin'),
    path('login/', index_login, name='test_index_login'),
    path('logout/', logout_user, name='test_logout'),
    path('singup/', signup_business, name='test_singup_business'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    path('addnew', addnew, name='test_addnew'),
    path('edit/<int:pk>/', edit, name='test_edit'),
    path('update/<int:pk>/', update, name='test_update'),
    path('delete/<int:pk>', delete, name='test_delete'),
    
    path('img/<int:pk>/', image_view, name='test_image_view'),
    path('sql/', get_list_place, name='test_sql'),
    
    path('payment_add/', payment_create, name='test_payment_create'),
    path('payment/', index_payment, name='test_index_payment'),
    path('payment/<int:pk>', payment, name='test_payment'),
    path('update_payment/<int:pk>', update_payment, name='test_update_payment'),
    path('update_profile/', update_profile, name='test_update_profile'),
    
    path('get_place_distance/<int:pk>/', get_list_place_with_distance, name='test_get_place_distance'),
    path('get_place_distance2/<int:pk>/<path:lat>/<path:lng>/<str:username>/', get_list_place_with_distance2, name='test_get_place_distance2'),
    path('get_sortPlace_with_tripBudget/<int:pk>/', getSortPlaceWithTripBudget, name='test_get_sortPlace_with_tripBudget'),
    path('get_sortPlace_with_usePlace/', getSorPlacetWithUsePlace, name='test_get_sortPlace_with_usePlace'),
    
    path('get_sortTrip_with_useTrip/', getSorTriptWithUseTrip, name='test_get_sortTrip_with_useTrip'),
    path('get_sortTrip_with_tripBudget/<path:budget>/', getSorTriptWithtripBudget, name='test_get_sortTrip_with_tripBudget'),
    path('get_list_trip_detail_clone/<int:pk>/', getListTripDetailClone, name='test_get_list_trip_detail_clone'),
    path('get_list_rac_place/<int:pk>/', getListRacPlace, name='test_get_list_rac_place'),
    
    path('get_list_trip_user_and_pic1/<str:username>/', getListTripUserAndPic1, name='test_get_list_trip_user_and_pic1'),
    
    path(
        'add_create_trip_clone/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<str:date_start>/<str:date_end>/<int:pkClone>/<str:username>/', 
        TripCloneViewAV.as_view(), 
        name='test_add_create_trip_clone'),
    
    path('add_create_trip_detail_clone/<int:pkMain>/<int:pkClone>/', addTripCloneDetail, name='test_add_create_trip_detail_clone'),
    
    path('report_business/', report, name='test_report_business'),
    path('report_business/<int:pk>/', open_report, name='test_open_report_business'),
    
    path('chkIn_TripDetailID/<int:pk>/<int:chkIn>/', TripDetailChkIn.as_view(), name='chkIn_TripDetailID'),
    path('chkIn_place_in_trip/<int:trip_id>/<int:place_id>/', chkPlaceInTrip, name='chkIn_place_in_trip'),
    path('chkIn_trip_detail/<int:pk>/', chkTripDetail, name='chkIn_trip_detail'),
    
    path('delete_trip/<int:pk>/', TripDeleteAV.as_view(), name='delete_trip'),
    path('add_rac_place/<int:score>/<str:comment>/<int:place_id>/<str:username>/', RacPlaceAV.as_view(), name='add_rac_place'),
    path(
        'update_trip_detail/<int:pk>/<str:name>/<str:detail>/<str:position_start>/<str:position_end>/<path:budget>/<int:permission>/<str:username>/<str:date_end>/<str:date_start>/', 
         TripDetailUpdateAV.as_view(), 
         name='update_trip_detail'
    ),
]

user_app/api/urls.py
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path
from plantrip_filnal import settings
from user_app.api.views import *

from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', home_view, name='home-view'),

    path('login/', obtain_auth_token, name='login'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='myapp_logout'),

    path('user_all/', UserViewAV.as_view(), name='user-all'),
    path('user/<int:pk>/', UserViewDetailAV.as_view(), name='user-detail'),
    path('user/<str:username>/', UserViewDetail.as_view(), name='user-detail-view'),
    
    path('about_us/', about_us_view, name='about-us-view'),
    path('chk_group_id/<str:username>/', ChkGroupID.as_view(), name='chkgroupid-view'),
]

test_app/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)
    
    class Meta:
        db_table = 'tblemployee'

class District(models.Model):
    name = models.CharField(max_length=100)
    lat = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    lng = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    
    class Meta:
        db_table = 'District'
        
    def __str__(self):
        return self.name + " | (" + str(self.lat) +", " + str(self.lng) + ")"

user_app/models.py
import datetime
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from django.contrib.auth.models import User
from django.db import models

from businessplace_app.models import BusinessPlace

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        
class AccountDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    address = models.TextField(null=True, blank=True)
    
    def __str__(self) :
        return str(self.user.username)
    

test_app/forms.py
from django import forms
from django.urls import reverse_lazy
from businessplace_app.models import BusinessPlace, BusinessType
from payment_app.models import Payment
from test_app.models import Employee

from django.contrib.auth.models import User
from datetime import datetime

class PaymentForm(forms.ModelForm):
    
    class Meta:
        model = Payment
        fields = ['upload_date', 'upload_img']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
        upload_img = forms.ImageField(
            widget=forms.ClearableFileInput(
                attrs={'class': 'form-control-file'}
            )
        )


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'image', 'image_url', ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
        image = forms.ImageField(
            widget=forms.ClearableFileInput(
                attrs={'class': 'form-control-file'}
            )
        )

class BusinessPlaceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        DISTRICT_CHOICES = [
            ('เมืองอุดรธานี', 'เมืองอุดรธานี'),
            ('กุดจับ', 'กุดจับ'),
            ('หนองวัวซอ', 'หนองวัวซอ'),
            ('กุมภวาปี', 'กุมภวาปี'),
            ('โนนสะอาด', 'โนนสะอาด'),
            ('หนองหาน', 'หนองหาน'),
            ('ทุ่งฝน', 'ทุ่งฝน'),
            ('ไชยวาน', 'ไชยวาน'),
            ('ศรีธาตุ', 'ศรีธาตุ'),
            ('วังสามหมอ', 'วังสามหมอ'),
            ('บ้านดุง', 'บ้านดุง'),
            ('บ้านผือ', 'บ้านผือ'),
            ('น้ำโสม', 'น้ำโสม'),
            ('เพ็ญ', 'เพ็ญ'),
            ('สร้างคอม', 'สร้างคอม'),
            ('หนองแสง', 'หนองแสง'),
            ('นายูง', 'นายูง'),
            ('พิบูลย์รักษ์', 'พิบูลย์รักษ์'),
            ('กู่แก้ว', 'กู่แก้ว'),
            ('ประจักษ์ศิลปาคม', 'ประจักษ์ศิลปาคม'),
        ]
        
        TYPE_CHOICES = [
            ('1', 'สถานที่ท่องเที่ยว'),
            ('2', 'ที่พัก'),
            ('3', 'ร้านหรือคาเฟ่'),
        ]

        # HOURS_CHOICES = [
        #     ('00', '00'),
        #     ('01', '01'),
        #     ('02', '02'),
        #     ('03', '03'),
        #     ('04', '04'),
        #     ('05', '05'),
        #     ('06', '06'),
        #     ('07', '07'),
        #     ('08', '08'),
        #     ('09', '09'),
        #     ('10', '10'),
        #     ('11', '11'),
        #     ('12', '12'),
        #     ('13', '13'),
        #     ('14', '14'),
        #     ('15', '15'),
        #     ('16', '16'),
        #     ('17', '17'),
        #     ('18', '18'),
        #     ('19', '19'),
        #     ('20', '20'),
        #     ('21', '21'),
        #     ('22', '22'),
        #     ('23', '23'),
        # ]
        
        # MINUTES_CHOICES = [
        #     ('00', '00'),
        #     ('01', '01'),
        #     ('02', '02'),
        #     ('03', '03'),
        #     ('04', '04'),
        #     ('05', '05'),
        #     ('06', '06'),
        #     ('07', '07'),
        #     ('08', '08'),
        #     ('09', '09'),
        #     ('10', '10'),
        #     ('11', '11'),
        #     ('12', '12'),
        #     ('13', '13'),
        #     ('14', '14'),
        #     ('15', '15'),
        #     ('16', '16'),
        #     ('17', '17'),
        #     ('18', '18'),
        #     ('19', '19'),
        #     ('20', '20'),
        #     ('21', '21'),
        #     ('22', '22'),
        #     ('23', '23'),
        #     ('24', '24'),
        #     ('25', '25'),
        #     ('26', '26'),
        #     ('27', '27'),
        #     ('28', '28'),
        #     ('29', '29'),
        #     ('30', '30'),
        #     ('31', '31'),
        #     ('32', '32'),
        #     ('33', '33'),
        #     ('34', '34'),
        #     ('35', '35'),
        #     ('36', '36'),
        #     ('37', '37'),
        #     ('38', '38'),
        #     ('39', '39'),
        #     ('40', '40'),
        #     ('41', '41'),
        #     ('42', '42'),
        #     ('43', '43'),
        #     ('44', '44'),
        #     ('45', '45'),
        #     ('46', '46'),
        #     ('47', '47'),
        #     ('48', '48'),
        #     ('49', '49'),
        #     ('50', '50'),
        #     ('51', '51'),
        #     ('52', '52'),
        #     ('53', '53'),
        #     ('54', '54'),
        #     ('55', '55'),
        #     ('56', '56'),
        #     ('57', '57'),
        #     ('58', '58'),
        #     ('59', '59'),
        #     ('60', '60'),
        # ]
    
        super().__init__(*args, **kwargs)

        self.fields['district'].widget = forms.Select(
            choices=DISTRICT_CHOICES, attrs={'class': 'form-control'})
        self.fields['type'].widget = forms.Select(
            choices=TYPE_CHOICES, attrs={'class': 'form-control'})
        self.fields['detail'].required = False
        self.fields['vr'].required = False
        self.fields['website'].required = False
        self.fields['timeOpen'].required = False
        self.fields['timeClose'].required = False

    class Meta:
        model = BusinessPlace

        fields = ['name', 'district', 'type', 'address', 'lat', 'lng',  'detail', 'timeOpen', 'timeClose',
                  'minPrice', 'maxPrice', 'website', 'pic1', 'pic2', 'pic3', 'vr', 'place_user']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'timeOpen': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'timeClose': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
            'vr': forms.URLInput(attrs={'class': 'form-control'},),
            'place_user': forms.NumberInput(attrs={'class': 'form-control'},),
        }
        detail = forms.CharField(required=False, widget=forms.Textarea(
            attrs={'class': 'form-label', 'rows': 4, 'cols': 40}, ), )
        
        pic1 = forms.ImageField(
            widget=forms.ClearableFileInput(
                attrs={'class': 'form-control-file', 'name': 'pic1'}
            )
        )
        pic2 = forms.ImageField(
            widget=forms.ClearableFileInput(
                attrs={'class': 'form-control-file', 'name': 'pic2'}
            )
        )
        pic3 = forms.ImageField(
            widget=forms.ClearableFileInput(
                attrs={'class': 'form-control-file', 'name': 'pic3'}
            )
        )
        
        lat = forms.FloatField(
            required=False, max_value=10, min_value=0,
            widget=forms.NumberInput(
                attrs={'class': 'form-label', 'type': 'number'}
            )
        )
        lng = forms.FloatField(
            required=False, max_value=10, min_value=0,
            widget=forms.NumberInput(
                attrs={'class': 'form-label', 'type': 'number'}
            )
        )
        
        minPrice = forms.FloatField(
            required=False, min_value=0,
            widget=forms.NumberInput(
                attrs={'class': 'form-label', 'type': 'number', 'step': 0.01}
            )
        )
        maxPrice = forms.FloatField(
            required=False, min_value=0,
            widget=forms.NumberInput(
                attrs={'class': 'form-label', 'type': 'number', 'ste': 0.01}
            )
        )

class BusinessPlaceEditForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        DISTRICT_CHOICES = [
            ('เมืองอุดรธานี', 'เมืองอุดรธานี'),
            ('กุดจับ', 'กุดจับ'),
            ('หนองวัวซอ', 'หนองวัวซอ'),
            ('กุมภวาปี', 'กุมภวาปี'),
            ('โนนสะอาด', 'โนนสะอาด'),
            ('หนองหาน', 'หนองหาน'),
            ('ทุ่งฝน', 'ทุ่งฝน'),
            ('ไชยวาน', 'ไชยวาน'),
            ('ศรีธาตุ', 'ศรีธาตุ'),
            ('วังสามหมอ', 'วังสามหมอ'),
            ('บ้านดุง', 'บ้านดุง'),
            ('บ้านผือ', 'บ้านผือ'),
            ('น้ำโสม', 'น้ำโสม'),
            ('เพ็ญ', 'เพ็ญ'),
            ('สร้างคอม', 'สร้างคอม'),
            ('หนองแสง', 'หนองแสง'),
            ('นายูง', 'นายูง'),
            ('พิบูลย์รักษ์', 'พิบูลย์รักษ์'),
            ('กู่แก้ว', 'กู่แก้ว'),
            ('ประจักษ์ศิลปาคม', 'ประจักษ์ศิลปาคม'),
        ]
        TYPE_CHOICES = [
            ('1', 'สถานที่ท่องเที่ยว'),
            ('2', 'ที่พัก'),
            ('3', 'ร้านหรือคาเฟ่'),
        ]
        
        HOURS_CHOICES = [
            ('00', '00'),
            ('01', '01'),
            ('02', '02'),
            ('03', '03'),
            ('04', '04'),
            ('05', '05'),
            ('06', '06'),
            ('07', '07'),
            ('08', '08'),
            ('09', '09'),
            ('10', '10'),
            ('11', '11'),
            ('12', '12'),
            ('13', '13'),
            ('14', '14'),
            ('15', '15'),
            ('16', '16'),
            ('17', '17'),
            ('18', '18'),
            ('19', '19'),
            ('20', '20'),
            ('21', '21'),
            ('22', '22'),
            ('23', '23'),
        ]
        
        MINUTES_CHOICES = [
            ('00', '00'),
            ('01', '01'),
            ('02', '02'),
            ('03', '03'),
            ('04', '04'),
            ('05', '05'),
            ('06', '06'),
            ('07', '07'),
            ('08', '08'),
            ('09', '09'),
            ('10', '10'),
            ('11', '11'),
            ('12', '12'),
            ('13', '13'),
            ('14', '14'),
            ('15', '15'),
            ('16', '16'),
            ('17', '17'),
            ('18', '18'),
            ('19', '19'),
            ('20', '20'),
            ('21', '21'),
            ('22', '22'),
            ('23', '23'),
            ('24', '24'),
            ('25', '25'),
            ('26', '26'),
            ('27', '27'),
            ('28', '28'),
            ('29', '29'),

test_app/templates/base_test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- bootstrap CND -->
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <style>
      @import url("https://fonts.googleapis.com/css2?family=Prompt&display=swap");
      * {
        font-family: "Prompt", sans-serif;
      }
      html {
        box-sizing: border-box;
        font-size: 16px;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }

      body,
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p,
      ol,
      ul {
        margin: 0;
        padding: 0;
        font-weight: normal;
      }

      ol,
      ul {
        list-style: none;
      }

      img {
        max-width: 100%;
        height: auto;
      }
    </style>

    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/styles.css' %}"
    />
  </head>
  <body>
    <div class="dashboard-container">
      <aside class="sidebar">
        <h1 class="text-white logo">
          Plan<span class="text-primary">Trip</span>
        </h1>
        สำหรับผู้ประกอบการ
        <hr />
        <ul class="menu">
          <li class="menu-item" id="homepage">
            <a id="id_home" class="class_link" href="{% url 'user:home-view' %}"
              >หน้าหลัก</a
            >
          </li>
          <li class="menu-item" id="editProfileUser">
            <a id="id_home" class="class_link" href="{% url 'test:test_update_profile' %}"
              >จัดโปรไฟล์</a
            >
          </li>
          <li class="menu-item" id="managePayment">
            <a id="id_home" class="class_link" href="{% url 'test:test_index_payment' %}"
              >จัดการค่าชำระบริการ</a
            >
          </li>
          <li class="menu-item" id="report">
            <a id="id_home" class="class_link" href="{% url 'user:home-view' %}"
              >รายงาน</a
            >
          </li>
          <li class="menu-item" id="logout">
            <a
              id="id_logout"
              class="class_link"
              href="{% url 'test:test_logout' %}"
              >ออกจากระบบ</a
            >
          </li>
        </ul>
      </aside>

      <main class="main-content">
        {% for message in messages %}

        <div class="container-fluid p-0">
          <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
            {{ message }}
          </div>
        </div>
        
        {% endfor %} {% block content %} {% endblock %}
      </main>
    </div>

    <!-- bootstrap CND -->
    <script
      src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"
      integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.7.0.js"
      integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

test_app/templates/img.html
<!DOCTYPE html>
<html>
<head>
    <title>Display Image</title>
</head>
<body>

<h2>Image:</h2>
<img src="{{ image_url }}" alt="Image">

</body>
</html>

test_app/templates/index.html
{% extends "base_test.html" %} {% block title %}หนัาหลัก{% endblock title %} {% block content %}
<header class="page-header">
  <h2>หนัาหลัก | ยินดีต้อนรับคุณ {{ username }}</h2>
</header>

<div class="dashboard-cards">
  <div class="card">
    <div
      class="card-body text-white rounded-bottom"
      style="background-color: #053b50"
    >
      <h5 class="card-title">กิจการการยอดนิยมสูงสุด</h5>
      <p class="card-text">
        {{place_use.place_name}} | ถูกนำไปจัดทริป {{ place_use.count_use_place }} ครั้ง
      </p>
    </div>
  </div>

  <div class="card">
    <div
      class="card-body text-white rounded-bottom"
      style="background-color: #176B87"
    >
      <h5 class="card-title">กิจการการยอดนิยมต่ำสุด</h5>
      <p class="card-text">
        {{place_use_nagative.place_name}} | ถูกนำไปจัดทริป {{ place_use_nagative.count_use_place }} ครั้ง
      </p>
    </div>
  </div>

  <div class="card">
    <div
      class="card-body text-white rounded-bottom"
      style="background-color: #64CCC5"
    >
      <h5 class="card-title">กิจการการที่คะแนนสูงสุด</h5>
      <p class="card-text">
        {{place_score.name}} | {{ place_score.score_place }} แต้ม
      </p>
    </div>
  </div>

  <div class="card">
    <div
      class="card-body text-white rounded-bottom"
      style="background-color: #e49393"
    >
      <h5 class="card-title">กิจการการที่คะแนนต่ำสุด</h5>
      <p class="card-text">
        {{place_score_nagative.name}} | {{ place_score_nagative.score_place }} แต้ม
      </p>
    </div>
  </div>
</div>

<div class="col-md-12 p-2">
  <span
    ><a href="{% url 'test:test_addnew' %}" class="btn btn-primary"
      >เพิ่มกิจการ</a
    ></span
  >
</div>
<form
  class="d-flex p-2"
  role="search"
  method="POST"
  action="{% url 'test:test_index' %}"
>
  {% csrf_token %}
  <input
    class="form-control me-2"
    type="search"
    placeholder="ชื่อกิจการ"
    name="search_query"
  />
  <button class="btn btn-outline-success" type="submit">ค้นหา</button>
</form>
<div class="table-responsive p-2">
  <table
    id="id_tblbussinessplace"
    class="table table-striped table-bordered"
    width="100%"
  >
    <thead>
      <th>รหัส</th>
      <th>ชื่อกิจการ</th>
      <th>อำเภอ</th>
      <th>ประเภท</th>
      <th>แก้ไขกิจการ</th>
      <th>ลบกิจการ</th>
    </thead>
    <tbody>
      {% for place in places%}
      <tr>
        <td>{{ place.id }}</td>
        <td>{{ place.name }}</td>
        <td>{{ place.district }}</td>
        <td>{{ place.type.detail }}</td>

        <td>
          <a
            href="{% url 'test:test_edit' pk=place.id %}"
            class="btn btn-warning btn-sm btn-block"
            name="confirm_delete"
            >แก้ไข</a
          >
        </td>
        <td>
          <a
            href="{% url 'test:test_delete' pk=place.id %}"
            class="btn btn-danger btn-sm btn-block btndel"
            onclick="return confirm('ยืนการลบกิจการ?')"
            >ลบ</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<center class="p-2">
  {%if places.has_previous %}
  <a href="?page={{places.previous_page_number}}"><</a>
  {% endif %} <span>{{places.number}}</span>
  {%if places.has_next %}
  <a href="?page={{places.next_page_number}}">></a>
  {% endif %}
</center>
{% endblock content %}

test_app/templates/payment.html
{% extends "base_test.html" %} {% block title %}จัดการการชำระค่าบริการ{% endblock title %} {% block content %}
<header class="page-header">
  <h2>จัดการการชำระค่าบริการ</h2>
</header>

<div class="table-responsive p-2">
  <table
    id="id_tblpayment"
    class="table table-striped table-bordered"
    width="100%"
  >
    <thead>
      <th>รหัส</th>
      <th>วันที่</th>
      <th>ราคา</th>
      <th>สถานนะการชำระ</th>
      <th></th>
    </thead>
    <tbody>
      {% for pay in payment%}
      <tr>
        <td>{{ pay.id }}</td>
        <td>{{ pay.payment_date.day }}/{{ pay.payment_date.month }}/{{ pay.payment_date.year }}</td>
        <td>{{ pay.price }}</td>
        <td>{{ pay.payment_status }}</td>
        
        <td>
          <a
            href="{% url 'test:test_payment' pk=pay.id %}"
            class="btn btn-warning btn-sm btn-block"
            name="confirm_open_payment"
            >ชำระ</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<center class="p-2">
  {%if pays.has_previous %} {# whether the previous page exists #}
      <a href="?page={{payment.previous_page_number}}"><</a> {# link to the prev page #}
  {% endif %}
  <span>{{pays.number}}</span> {# the current page number #}
 
  {%if pays.has_next %} {# whether the next page exists #}
      <a href="?page={{payment.next_page_number}}">></a> {# link to the next page #}
  {% endif %}
</center>
{% endblock content %}